clouddrivers:
  - name: clouddriver-1
    url: http://clouddriver:7002
    healthcheckUrl: http://clouddriver:7002/health
  - name: clouddriver-2
    url: http://clouddriver2:7002
  - name: cloudOnlyDriver
    url: http://go-clouddriver:7002
    disableArtifactAccounts: true
    priority: 100
