# Default values are shown if not set.

#spinnakerUser: anonymous # default value
#httpListenPort: 7002 # default value

clouddrivers:
  - name: clouddriver-1 # name is required
    url: http://clouddriver:7002 # url is required
    healthcheckUrl: http://clouddriver:7002/health # default is url + "/health"
  - name: clouddriver-2
    url: http://clouddriver2:7002
    uiUrl: https://example.com/spinnaker-frontend # used in the UI
  - name: cloudOnlyDriver
    url: http://go-clouddriver:7002
    disableArtifactAccounts: true # default is false
    priority: 100 # default is 0

# When making external requests to clouddrivers, timeouts
# and other parameters can be set on the http client
# Stormdriver will use.
# httpClientConfig:
#   dialTimeout: 15 # value in seconds
#   clientTimeout: 60 # value in seconds
#   tlsHandshakeTimeout: 15 # value in seconds
#   responseTimeout: 60 # value in seconds
#   maxIdleConnections: 5 # count of unused left-open sessions to remotes

# If using a controller to track connected clouddriver services,
# the URL is required.  Others have defaults, but those paths
# must be populated with the correct files.
# controller:
#   url: https://controller.example.com:9003
#   caPath: /app/secrets/controller-ca.crt # default
#   certificatePath: /app/secrets/controller-control/tls.crt # default
#   keyPath: /app/secrets/controller-control/tls.key # default
#   updateFrequencySeconds: 30 # default
